import { createContext, useContext, useState, useEffect, ReactNode } from "react";

export type Language = "vi" | "en";

interface LanguageContextType {
  lang: Language;
  setLang: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | null>(null);

// ─── Translation Dictionary ────────────────────────────────────────────────
const translations: Record<Language, Record<string, string>> = {
  vi: {
    // Nav
    "nav.home": "Trang chủ",
    "nav.rooms": "Phòng nghỉ",
    "nav.amenities": "Tiện nghi",
    "nav.offers": "Ưu đãi",
    "nav.explore": "Khám phá Huế",
    "nav.loyalty": "Loyalty",
    "nav.about": "Giới thiệu",
    "nav.contact": "Liên hệ",
    "nav.book_now": "Đặt phòng ngay",
    "nav.points": "điểm",

    // Hero
    "hero.welcome": "WELCOME TO",
    "hero.tagline": "Your cozy retreat in the heart of Hue",
    "hero.badge1": "Comfortable Rooms",
    "hero.badge2": "Prime Location",
    "hero.badge3": "3-Star Comfort",
    "hero.chat_placeholder": "Chào bạn, bạn đang tìm kiếm một kỳ nghỉ như thế nào?",
    "hero.checkin": "Nhận phòng",
    "hero.checkout": "Trả phòng",
    "hero.guests": "Khách",
    "hero.search": "Tìm kiếm",
    "hero.guests_format": "{adults} khách, {rooms} phòng",

    // Features
    "features.title": "Trải nghiệm đặc biệt tại The Imperial Hue",
    "features.subtitle": "Nơi lưu trú lý tưởng kết hợp sự tiện nghi hiện đại với văn hóa cố đô",
    "features.f1_title": "Vị trí trung tâm",
    "features.f1_desc": "Ngay trung tâm Huế, gần Đại Nội, chợ Đông Ba và các điểm du lịch nổi tiếng",
    "features.f2_title": "Phòng nghỉ ấm cúng",
    "features.f2_desc": "Thiết kế hiện đại với nét duyên dáng xứ Huế",
    "features.f3_title": "Trải nghiệm địa phương",
    "features.f3_desc": "Gợi ý hành trình, ẩm thực và văn hóa đặc sắc của Huế",
    "features.f4_title": "Dịch vụ tận tâm",
    "features.f4_desc": "Đội ngũ thân thiện, luôn sẵn sàng đồng hành cùng bạn",

    // Rooms section
    "rooms.title": "Phòng nghỉ của chúng tôi",
    "rooms.subtitle": "Lựa chọn không gian lưu trú phù hợp với nhu cầu của bạn",
    "rooms.view_all": "Xem tất cả phòng",
    "rooms.book": "Đặt phòng",
    "rooms.from": "Từ",
    "rooms.guests": "khách",
    "rooms.sqm": "m²",
    "rooms.high_season": "Cao điểm",
    "rooms.discount": "Giá ưu đãi",
    "rooms.original_price": "Giá gốc",

    // Booking
    "booking.title": "Đặt phòng",
    "booking.room": "Phòng",
    "booking.checkin": "Ngày nhận phòng",
    "booking.checkout": "Ngày trả phòng",
    "booking.guests": "Số khách",
    "booking.name": "Họ và tên",
    "booking.email": "Email",
    "booking.phone": "Số điện thoại",
    "booking.notes": "Ghi chú",
    "booking.notes_placeholder": "Yêu cầu đặc biệt, giờ đến dự kiến...",
    "booking.nights": "đêm",
    "booking.total": "Tổng cộng",
    "booking.submit": "Xác nhận đặt phòng",
    "booking.success": "Đặt phòng thành công!",
    "booking.success_msg": "Chúng tôi sẽ liên hệ xác nhận trong vòng 24 giờ.",
    "booking.login_required": "Vui lòng đăng nhập để đặt phòng",
    "booking.login_btn": "Đăng nhập để đặt phòng",
    "booking.price_breakdown": "Chi tiết giá",
    "booking.base_price": "Giá cơ bản",
    "booking.multiplier": "Hệ số giá",
    "booking.dynamic_price": "Giá áp dụng",

    // Rooms page
    "rooms_page.title": "Phòng nghỉ",
    "rooms_page.subtitle": "Khám phá không gian lưu trú tinh tế tại The Imperial Hue",
    "rooms_page.filter_all": "Tất cả",
    "rooms_page.sort_price_asc": "Giá thấp đến cao",
    "rooms_page.sort_price_desc": "Giá cao đến thấp",
    "rooms_page.sort_size": "Diện tích",
    "rooms_page.no_rooms": "Không tìm thấy phòng phù hợp",
    "rooms_page.available": "Còn phòng",
    "rooms_page.unavailable": "Hết phòng",

    // Room detail
    "room_detail.back": "Quay lại",
    "room_detail.book_now": "Đặt phòng ngay",
    "room_detail.amenities": "Tiện nghi phòng",
    "room_detail.description": "Mô tả",
    "room_detail.capacity": "Sức chứa",
    "room_detail.size": "Diện tích",
    "room_detail.bed": "Giường",

    // Loyalty
    "loyalty.title": "Chương trình Loyalty",
    "loyalty.points": "Điểm thưởng",
    "loyalty.history": "Lịch sử điểm",
    "loyalty.redeem": "Đổi điểm",
    "loyalty.login_required": "Đăng nhập để xem điểm thưởng",

    // Common
    "common.loading": "Đang tải...",
    "common.error": "Có lỗi xảy ra",
    "common.back": "Quay lại",
    "common.save": "Lưu",
    "common.cancel": "Hủy",
    "common.confirm": "Xác nhận",
    "common.close": "Đóng",
    "common.night": "đêm",
    "common.nights": "đêm",
    "common.per_night": "/đêm",
    "common.vnd": "₫",
    "common.login": "Đăng nhập",
    "common.logout": "Đăng xuất",
    "common.guest": "Khách",
    "common.guests": "khách",
    "common.room": "phòng",
    "common.rooms": "phòng",

    // Trust badges
    "trust.best_price": "Best Price Guarantee",
    "trust.best_price_desc": "Cam kết giá tốt nhất",
    "trust.free_cancel": "Miễn phí hủy phòng",
    "trust.free_cancel_desc": "Hủy miễn phí trước 48h",
    "trust.breakfast": "Bữa sáng miễn phí",
    "trust.breakfast_desc": "Buffet đặc sản Huế mỗi ngày",
    "trust.wifi": "Wi-Fi miễn phí",
    "trust.wifi_desc": "Tốc độ cao toàn khách sạn",

    // Amenities page
    "amenities.title": "Tiện nghi & Dịch vụ",
    "amenities.subtitle": "Trải nghiệm đầy đủ tiện nghi hiện đại kết hợp nét duyên dáng văn hoá Huế, mang đến kỳ nghỉ thoải mái và đáng nhớ.",
    "amenities.standard": "Tiêu chuẩn 3 sao",
    "amenities.support": "Hỗ trợ",
    "amenities.rating": "Đánh giá",
    "amenities.room_amenities": "Tiện nghi trong phòng",
    "amenities.hotel_facilities": "Cơ sở vật chất khách sạn",
    "amenities.services": "Dịch vụ & Tiện ích",
    "amenities.dining": "Ẩm thực",
    "amenities.wellness": "Thể thao & Sức khoẻ",
    "amenities.wifi": "Wi-Fi tốc độ cao",
    "amenities.wifi_desc": "Miễn phí toàn khách sạn, tốc độ 100Mbps",
    "amenities.ac": "Điều hoà trung tâm",
    "amenities.ac_desc": "Điều chỉnh nhiệt độ riêng từng phòng",
    "amenities.tv": "Smart TV 43 inch",
    "amenities.tv_desc": "Hỗ trợ Netflix, YouTube và truyền hình cáp",
    "amenities.safe": "Két an toàn",
    "amenities.safe_desc": "Két điện tử trong phòng cho mỗi phòng",
    "amenities.breakfast": "Bữa sáng miễn phí",
    "amenities.breakfast_desc": "Buffet đặc sản Huế mỗi sáng từ 6:30 – 10:00",
    "amenities.restaurant": "Nhà hàng The Garden",
    "amenities.restaurant_desc": "Phục vụ ẩm thực Huế và quốc tế từ 11:00 – 22:00",
    "amenities.cafe": "Café & Bar Imperial",
    "amenities.cafe_desc": "Cà phê, cocktail và đồ uống từ 7:00 – 23:00",
    "amenities.room_service": "Room Service 24/7",
    "amenities.room_service_desc": "Đặt đồ ăn và đồ uống tại phòng bất kỳ lúc nào",
    "amenities.pool": "Hồ bơi ngoài trời",
    "amenities.pool_desc": "Hồ bơi 25m, mở cửa từ 6:00 – 21:00",
    "amenities.gym": "Phòng gym hiện đại",
    "amenities.gym_desc": "Trang thiết bị đầy đủ, mở cửa 24/7",
    "amenities.spa": "Spa & Massage",
    "amenities.spa_desc": "Liệu pháp thư giãn truyền thống Huế",
    "amenities.sauna": "Sauna & Steam Room",
    "amenities.sauna_desc": "Phòng xông hơi khô và ướt",
    "amenities.airport": "Đưa đón sân bay",
    "amenities.airport_desc": "Xe riêng đưa đón sân bay Phú Bài",
    "amenities.parking": "Bãi đỗ xe miễn phí",
    "amenities.parking_desc": "Bãi đỗ xe có mái che cho khách lưu trú",
    "amenities.tours": "Tour tham quan Huế",
    "amenities.tours_desc": "Đặt tour tham quan Đại Nội, lăng tẩm, sông Hương",
    "amenities.reception": "Lễ tân 24/7",
    "amenities.reception_desc": "Hỗ trợ check-in/check-out và tư vấn du lịch",
    "amenities.cta_title": "Sẵn sàng trải nghiệm?",
    "amenities.cta_desc": "Đặt phòng ngay hôm nay và tận hưởng toàn bộ tiện nghi cao cấp tại The Imperial Hue.",
    "amenities.cta_btn": "Xem phòng & Đặt ngay",

    // Offers page
    "offers.subtitle": "Khám phá các gói ưu đãi hấp dẫn tại The Imperial Hue",

    // Explore page
    "explore.title": "Khám phá Huế",
    "explore.subtitle": "Những điểm đến không thể bỏ lỡ tại cố đô Huế",

    // About page
    "about.title": "Giới thiệu",
    "about.subtitle": "Câu chuyện của The Imperial Hue",

    // Contact page
    "contact.subtitle": "Chúng tôi luôn sẵn sàng hỗ trợ bạn",

    // Chat
    "chat.placeholder": "Bạn cần hỗ trợ gì?",
    "chat.error": "Xin lỗi, tôi gặp sự cố. Vui lòng thử lại!",
    "chat.q1": "Tìm phòng",
    "chat.q1_sub": "Kiểm tra phòng trống",
    "chat.q1_msg": "Tôi muốn tìm phòng trống",
    "chat.q2": "Ưu đãi đặc biệt",
    "chat.q2_sub": "Khám phá ưu đãi mới nhất",
    "chat.q2_msg": "Có ưu đãi gì đặc biệt không?",
    "chat.q3": "Dịch vụ của chúng tôi",
    "chat.q3_sub": "Khám phá tiện ích & dịch vụ",
    "chat.q3_msg": "Khách sạn có những dịch vụ gì?",
    "chat.q4": "Hỗ trợ ngay",
    "chat.q4_sub": "Chúng tôi luôn sẵn sàng!",
    "chat.q4_msg": "Tôi cần hỗ trợ",

    // Rooms page extra
    "rooms_page.search_placeholder": "Tìm tên phòng...",
    "rooms_page.guests_label": "Số khách",
    "rooms_page.sort_label": "Sắp xếp",
    "rooms_page.price": "Giá",
    "rooms_page.try_other": "Thử thay đổi bộ lọc hoặc tìm kiếm khác",
    "rooms_page.rooms_found": "phòng phù hợp",
    "rooms_page.people_viewing": "người đang xem",
    "rooms.view_details": "Xem chi tiết",
    "rooms.tooltip": "Phòng này thường hết chỗ vào cuối tuần, bạn có muốn xem lịch trống không?",

    // Returning visitor
    "returning.best_price_kept": "Chúng tôi vẫn giữ",
    "returning.room_viewed": "Phòng bạn đã xem",
    "returning.view_rooms": "Xem phòng",
    "chat.special_offer_for_you": "Ưu đãi đặc biệt chỉ dành riêng cho bạn!",
    "chat.view_offers": "Xem ưu đãi →",
    "chat.welcome_message": "Xin chào! 👋 Tôi là Imperial AI, trợ lý của khách sạn The Imperial Hue. Tôi có thể giúp bạn tìm phòng phù hợp hoặc trả lời các câu hỏi về khách sạn. Bạn cần gì?",
    "chat.error_message": "Xin lỗi, có lỗi xảy ra. Vui lòng thử lại.",
    "chat.input_placeholder": "Nhập câu hỏi...",
    "chat.mobile_placeholder": "Hỏi AI về phòng...",
    "chat.support_247": "Hỗ trợ 24/7",
    "exit.limited_offer": "Ưu đãi giới hạn",
    "exit.wait_title": "Khoan đã! Chúng tôi có",
    "exit.special_offer": "ưu đãi đặc biệt",
    "exit.for_you": "cho bạn",
    "exit.room_viewing": "Phòng bạn đang xem",
    "exit.today_special": "Ưu đãi đặc biệt hôm nay",
    "exit.discount_all": "Giảm 15% tất cả phòng",
    "exit.book_today": "Áp dụng khi đặt phòng trong hôm nay",
    "exit.expires_in": "Ưu đãi hết hạn sau:",
    "exit.claim_now": "Nhận ưu đãi ngay →",
    "exit.no_thanks": "Không, tôi không cần ưu đãi",
    "returning.welcome": "Chào mừng bạn trở lại!",
    "returning.kept": "Chúng tôi vẫn giữ",
    "returning.best_price": "mức giá tốt nhất",
    "returning.for_you": "cho bạn.",
    "returning.new_offers": "Ưu đãi mới",

    // Room detail extra
    "room_detail.people_viewing": "người đang xem phòng này",
    "room_detail.price_per_night": "/đêm",
    "room_detail.select_dates": "Chọn ngày để đặt phòng",
    "room_detail.similar_rooms": "Phòng tương tự",
    "room_detail.reviews": "Đánh giá",
    "room_detail.location": "Vị trí",
    "room_detail.policies": "Chính sách",
    "room_detail.checkin_time": "Nhận phòng: 14:00",
    "room_detail.checkout_time": "Trả phòng: 12:00",
    "room_detail.no_smoking": "Không hút thuốc",
    "room_detail.pets": "Không mang thú cưng",

    // Booking extra
    "booking.special_requests": "Yêu cầu đặc biệt",
    "booking.payment_info": "Thông tin thanh toán",
    "booking.pay_at_hotel": "Thanh toán tại khách sạn",
    "booking.booking_policy": "Chính sách đặt phòng",
    "booking.free_cancel_48h": "Hủy miễn phí trước 48 giờ",
    "booking.confirm_info": "Xác nhận thông tin",

    // About page extra
    "about.story": "Câu chuyện của chúng tôi",
    "about.story_desc": "The Imperial Hue được thành lập với tình yêu dành cho cố đô Huế, mong muốn mang đến trải nghiệm lưu trú ấm cúng và đậm chất văn hóa cho du khách.",
    "about.mission": "Sứ mệnh",
    "about.mission_desc": "Mang đến trải nghiệm lưu trú thoải mái, kết hợp nét đẹp truyền thống Huế với tiện nghi hiện đại.",
    "about.values": "Giá trị cốt lõi",
    "about.value1": "Tận tâm phục vụ",
    "about.value2": "Bảo tồn văn hóa",
    "about.value3": "Phát triển bền vững",

    // Contact page extra
    "contact.address_value": "15 Lý Thường Kiệt, TP. Huế, Thừa Thiên Huế",
    "contact.phone": "Điện thoại",
    "contact.email": "Email",
    "contact.send_message": "Gửi tin nhắn",
    "contact.your_name": "Tên của bạn",
    "contact.your_email": "Email của bạn",
    "contact.message": "Nội dung tin nhắn",
    "contact.send": "Gửi",

    // Offers page extraa
    "offers.valid_until": "Có hiệu lực đến",
    "offers.terms": "Điều khoản áp dụng",

    // Explore page extra
    "explore.distance": "Khoảng cách",
    "explore.from_hotel": "từ khách sạn",
    "explore.view_map": "Xem bản đồ",
    "explore.must_visit": "Phải đến",
    "explore.ancient_capital": "Cố đô Huế",
    "explore.hero_desc": "Khám phá những điểm đến tuyệt vời, ẩm thực đặc sắc và trải nghiệm văn hóa độc đáo tại Huế",
    "explore.top_attractions": "Điểm tham quan nổi bật",
    "explore.near_hotel": "Gần khách sạn",
    "explore.citadel": "Đại Nội - Kinh thành Huế",
    "explore.citadel_desc": "Di sản thế giới UNESCO, quần thể cung điện hoàng gia triều Nguyễn với kiến trúc độc đáo",
    "explore.perfume_river_bridge": "Sông Hương & Cầu Trường Tiền",
    "explore.perfume_river_desc": "Biểu tượng lãng mạn của Huế, đẹp nhất khi hoàng hôn buông xuống",
    "explore.tuduc": "Lăng Tự Đức",
    "explore.tuduc_desc": "Lăng tẩm đẹp nhất Huế với kiến trúc hài hòa giữa thiên nhiên và nghệ thuật",
    "explore.thienmu": "Chùa Thiên Mụ",
    "explore.thienmu_desc": "Ngôi chùa cổ nhất Huế, biểu tượng tâm linh bên bờ sông Hương",
    "explore.cat_history": "Lịch sử",
    "explore.cat_nature": "Thiên nhiên",
    "explore.cat_spiritual": "Tâm linh",
    "explore.hours_3_4": "3-4 giờ",
    "explore.hours_2_3": "2-3 giờ",
    "explore.hours_1_2": "1-2 giờ",
    "explore.featured": "Nổi bật",
    "explore.architecture": "Kiến trúc",
    "explore.local_cuisine": "Ẩm thực Huế",
    "explore.bun_bo": "Bún bò Huế",
    "explore.bun_bo_desc": "Món ăn đặc trưng nhất của Huế với nước dùng đậm đà, sả và ớt",
    "explore.bun_bo_where": "Bà Phượng, 323 Nguyễn Sinh Cung",
    "explore.com_hen": "Cơm hến",
    "explore.com_hen_desc": "Cơm trộn hến sông Hương, rau sống và nước mắm cay",
    "explore.com_hen_where": "Chợ Đông Ba, đường Trần Hưng Đạo",
    "explore.banh_khoai": "Bánh khoái",
    "explore.banh_khoai_desc": "Bánh giòn nhân tôm thịt, chấm nước lèo đặc biệt",
    "explore.banh_khoai_where": "Hàng Me, 11 Phó Đức Chính",
    "explore.che_hue": "Chè Huế",
    "explore.che_hue_desc": "Hơn 30 loại chè truyền thống, ngọt thanh và đầy màu sắc",
    "explore.che_hue_where": "Chè Hẻm, 17 Hùng Vương",
    "explore.experiences": "Trải nghiệm tại Huế",
    "explore.act_bike": "Đạp xe khám phá",
    "explore.act_bike_desc": "Thuê xe đạp tại khách sạn, khám phá phố cổ và làng nghề truyền thống",
    "explore.act_photo": "Chụp ảnh áo dài",
    "explore.act_photo_desc": "Thuê áo dài và chụp ảnh tại Đại Nội, lăng tẩm và các địa điểm đẹp",
    "explore.act_cooking": "Học nấu ăn Huế",
    "explore.act_cooking_desc": "Tham gia lớp học nấu ăn với đầu bếp địa phương, học làm bánh bèo, bánh nậm",
    "explore.act_cruise": "Du thuyền sông Hương",
    "explore.act_cruise_desc": "Ngắm hoàng hôn trên sông Hương, thưởng thức ca Huế trên thuyền",
    "explore.hotel_location": "Vị trí khách sạn",
    "explore.hotel_address": "123 Lê Lợi, Vĩnh Ninh, TP. Huế",
    "explore.hotel_nearby": "Cách Đại Nội 500m • Cách sông Hương 300m",


    // About page
    "about.hero_title": "Giới thiệu về\nThe Imperial Hue",
    "about.hero_desc": "Được thành lập năm 2015 với tình yêu dành cho mảnh đất cố đô, The Imperial Hue Boutique Hotel là nơi giao thoa giữa nét cổ kính của kinh thành Huế và sự tiện nghi hiện đại.",
    "about.stat_years": "Năm kinh nghiệm",
    "about.stat_rooms": "Phòng nghỉ",
    "about.stat_guests": "Lượt khách",
    "about.stat_rating": "Đánh giá trung bình",
    "about.story_title": "Câu chuyện hình thành",
    "about.story_p1": "The Imperial Hue ra đời từ ước mơ của những người con xứ Huế muốn giới thiệu vẻ đẹp của quê hương đến bạn bè trong nước và quốc tế. Tọa lạc ngay trung tâm thành phố, cách Đại Nội chỉ 500 mét.",
    "about.story_p2": "Với 60 phòng nghỉ được trang bị đầy đủ tiện nghi hiện đại, nhà hàng phục vụ ẩm thực cung đình Huế và đội ngũ nhân viên nhiệt tình, The Imperial Hue đã trở thành điểm đến yêu thích.",
    "about.story_p3": "Năm 2024, chúng tôi tiên phong ứng dụng AI Agent vào dịch vụ khách sạn – giúp khách hàng tìm phòng, đặt dịch vụ và khám phá Huế một cách thông minh hơn.",
    "about.value1_title": "Hiếu khách như người thân",
    "about.value1_desc": "Mỗi khách hàng là một người thân. Chúng tôi lắng nghe và đáp ứng từng nhu cầu nhỏ nhất.",
    "about.value2_title": "Chất lượng nhất quán",
    "about.value2_desc": "Tiêu chuẩn 3 sao được duy trì nghiêm ngặt trong từng chi tiết.",
    "about.value3_title": "Bản sắc địa phương",
    "about.value3_desc": "Chúng tôi tự hào mang văn hoá Huế vào từng trải nghiệm.",
    "about.value4_title": "Đổi mới liên tục",
    "about.value4_desc": "Ứng dụng công nghệ AI để cá nhân hoá trải nghiệm.",
    "about.timeline_title": "Hành trình phát triển",
    "about.milestone_2015": "Thành lập The Imperial Hue Boutique Hotel với 30 phòng",
    "about.milestone_2017": "Mở rộng lên 60 phòng, đạt chứng nhận 3 sao quốc gia",
    "about.milestone_2019": "Nhận giải thưởng 'Khách sạn Boutique tốt nhất miền Trung'",
    "about.milestone_2022": "Ra mắt nhà hàng The Garden, phục vụ ẩm thực cung đình Huế",
    "about.milestone_2024": "Tích hợp AI Agent – trợ lý du lịch thông minh đầu tiên tại Huế",
    "about.team_title": "Đội ngũ lãnh đạo",
    "about.team1_name": "Nguyễn Minh Tuấn",
    "about.team1_role": "Tổng Giám đốc",
    "about.team1_desc": "15 năm kinh nghiệm trong ngành khách sạn cao cấp.",
    "about.team2_name": "Trần Thị Lan Anh",
    "about.team2_role": "Giám đốc Dịch vụ",
    "about.team2_desc": "Chuyên gia về trải nghiệm khách hàng.",
    "about.team3_name": "Lê Quang Huy",
    "about.team3_role": "Bếp trưởng",
    "about.team3_desc": "Đầu bếp chuyên về ẩm thực cung đình Huế.",
    "about.team4_name": "Phạm Thị Thu Hà",
    "about.team4_role": "Trưởng phòng Marketing",
    "about.team4_desc": "Chuyên gia digital marketing.",

    // Contact page full
    "contact.support_247": "Hỗ trợ 24/7",
    "contact.reply_2h": "Phản hồi trong 2 giờ",
    "contact.city_hue": "TP. Huế, Thừa Thiên Huế",
    "contact.hours": "Giờ làm việc",
    "contact.reception_247": "Lễ tân 24/7",
    "contact.checkin_checkout_time": "Check-in từ 14:00 | Check-out 12:00",
    "contact.always_ready": "Luôn sẵn sàng hỗ trợ",
    "contact.title": "Liên hệ với chúng tôi",
    "contact.hero_desc": "Đội ngũ The Imperial Hue luôn sẵn sàng hỗ trợ bạn 24/7.",
    "contact.follow_us": "Theo dõi chúng tôi",
    "contact.view_on_maps": "Xem trên Google Maps →",
    "contact.success_title": "Gửi thành công!",
    "contact.success_desc": "Cảm ơn bạn đã liên hệ. Chúng tôi sẽ phản hồi trong vòng 2 giờ làm việc.",
    "contact.send_another": "Gửi tin nhắn khác",
    "contact.form_desc": "Điền thông tin bên dưới, chúng tôi sẽ liên hệ lại sớm nhất.",
    "contact.fullname": "Họ và tên",
    "contact.fullname_placeholder": "Nguyễn Văn A",
    "contact.subject": "Chủ đề",
    "contact.select_subject": "Chọn chủ đề...",
    "contact.subject_booking": "Đặt phòng & Giá cả",
    "contact.subject_service": "Dịch vụ & Tiện nghi",
    "contact.subject_event": "Tổ chức sự kiện",
    "contact.subject_feedback": "Góp ý & Phản hồi",
    "contact.subject_other": "Khác",
    "contact.message_placeholder": "Mô tả chi tiết yêu cầu của bạn...",
    "contact.address": "Địa chỉ",

    // Booking page full
    "booking.invalid_room": "Phòng không hợp lệ",
    "booking.fill_all_fields": "Vui lòng điền đầy đủ thông tin",
    "booking.success_message": "Đặt phòng thành công! Chúng tôi sẽ liên hệ với bạn sớm.",
    "booking.error_message": "Lỗi khi đặt phòng. Vui lòng thử lại.",
    "booking.room_not_found": "Phòng không tìm thấy",
    "booking.guest_name": "Tên khách hàng",
    "booking.guest_name_placeholder": "Nhập tên của bạn",
    "booking.guest_unit": "khách",
    "booking.ai_support_title": "💡 Bạn cần hỗ trợ? Chúng tôi có thể giúp bạn hoàn tất đặt phòng!",
    "booking.ai_support_desc": "Nhấn nút chat ở góc dưới phải để trao đổi với AI Assistant.",
    "booking.submitting": "Đang xử lý...",
    "booking.confirm_booking": "Xác nhận đặt phòng",
    "booking.go_back": "Quay lại",
    "booking.price_summary": "Tóm tắt giá",
    "booking.calculating_price": "Đang tính giá động...",
    "booking.base_price_night": "Giá gốc/đêm",
    "booking.night": "đêm",
    "booking.num_nights": "Số đêm",
    "booking.savings": "Tiết kiệm",

    // Loyalty page full
    "loyalty.perk_earn_1x": "Tích điểm 1x",
    "loyalty.perk_earn_2x": "Tích điểm 2x",
    "loyalty.perk_birthday_10": "Sinh nhật +10%",
    "loyalty.perk_birthday_15": "Sinh nhật +15%",
    "loyalty.perk_birthday_20": "Sinh nhật +20%",
    "loyalty.perk_birthday_30": "Sinh nhật +30%",
    "loyalty.perk_early_checkin": "Early check-in",
    "loyalty.perk_early_checkin_priority": "Early check-in ưu tiên",
    "loyalty.perk_late_checkout_14": "Late checkout 14:00",
    "loyalty.perk_late_checkout_16": "Late checkout 16:00",
    "loyalty.perk_room_upgrade": "Nâng cấp phòng",
    "loyalty.perk_suite_upgrade": "Nâng cấp Suite",
    "loyalty.perk_free_minibar": "Minibar miễn phí",
    "loyalty.perk_flexible_checkin": "Check-in linh hoạt",
    "loyalty.perk_concierge": "Concierge riêng",
    "loyalty.perk_free_spa": "Spa miễn phí",
    "loyalty.reward_discount_100k": "Giảm 100.000đ",
    "loyalty.reward_breakfast": "Bữa sáng miễn phí",
    "loyalty.reward_room_upgrade": "Nâng cấp phòng",
    "loyalty.reward_airport_transfer": "Đưa đón sân bay",
    "loyalty.reward_spa_60": "Spa 60 phút",
    "loyalty.reward_free_night": "1 đêm miễn phí",
    "loyalty.login_desc": "Đăng nhập để xem điểm thưởng và đổi quà.",
    "loyalty.login_now": "Đăng nhập ngay",
    "loyalty.subtitle": "Tích điểm, đổi quà, tận hưởng ưu đãi đặc biệt",
    "loyalty.tier": "Hạng thành viên",
    "loyalty.current_points": "Điểm hiện tại",
    "loyalty.total_earned": "Tổng tích lũy",
    "loyalty.points_unit": "điểm",
    "loyalty.points_more": "điểm nữa",
    "loyalty.redeem_rewards": "Đổi điểm lấy quà",
    "loyalty.confirm_redeem": "Xác nhận đổi",
    "loyalty.processing": "Đang xử lý...",
    "loyalty.confirm": "Xác nhận",
    "loyalty.cancel": "Hủy",
    "loyalty.redeem_now": "Đổi ngay",
    "loyalty.need_more": "Cần thêm",
    "loyalty.no_transactions": "Chưa có giao dịch nào",
    "loyalty.no_account": "Chưa có tài khoản Loyalty",
    "loyalty.no_account_desc": "Đặt phòng đầu tiên để bắt đầu tích điểm.",

    // Rooms page
    "rooms.filter_all": "Tất cả",
    "rooms.sort_price_asc": "Giá tăng dần",
    "rooms.sort_price_desc": "Giá giảm dần",
    "rooms.sort_capacity": "Sức chứa",
    "rooms.per_night": "/đêm",
    "rooms.no_rooms": "Không tìm thấy phòng nào",
    "rooms_page.ai_tooltip": "Phòng này thường hết chỗ vào cuối tuần, bạn có muốn xem lịch trống không?",
    "rooms_page.clear_filter": "Xóa bộ lọc",
    "offers.badge_popular": "Phổ biến nhất",
    "offers.badge_family": "Gia đình",
    "offers.badge_savings": "Tiết kiệm",
    "offers.badge_longstay": "Dài hạn",
    "offers.honeymoon_title": "Gói Tuần Trăng Mật",
    "offers.honeymoon_desc": "Trọn vẹn kỳ nghỉ lãng mạn tại Huế cùng người thương. Bao gồm phòng Deluxe Balcony, bữa tối riêng tư bên sông Hương, hoa tươi và rượu vang chào mừng.",
    "offers.family_title": "Gói Gia Đình Vui Vẻ",
    "offers.family_desc": "Kỳ nghỉ trọn vẹn cho cả gia đình với phòng rộng rãi, bữa sáng buffet và các hoạt động khám phá Huế thú vị dành cho trẻ em.",
    "offers.weekend_title": "Gói Nghỉ Dưỡng Cuối Tuần",
    "offers.weekend_desc": "Thoát khỏi nhịp sống bận rộn, tận hưởng 2 ngày cuối tuần thư giãn tại The Imperial Hue với đầy đủ tiện ích và dịch vụ chăm sóc.",
    "offers.business_title": "Gói Công Tác Dài Ngày",
    "offers.business_desc": "Lý tưởng cho khách công tác hoặc du lịch dài ngày. Được hưởng giá ưu đãi đặc biệt khi lưu trú từ 5 đêm trở lên.",
    "offers.flash_friday": "Flash Sale Thứ 6",
    "offers.flash_friday_desc": "Giảm 30% tất cả phòng đặt trong ngày thứ 6",
    "offers.flash_friday_expires": "Còn 2 ngày",
    "offers.early_bird_desc": "Đặt trước 30 ngày, tiết kiệm 25%",
    "offers.early_bird_expires": "Luôn có",
    "offers.last_minute_desc": "Phòng trống hôm nay, giảm 15% khi đặt trước 18:00",
    "offers.last_minute_expires": "Hôm nay",
    "offers.special_tag": "Ưu đãi đặc biệt",
    "offers.title": "Ưu đãi & Khuyến mãi",
    "offers.hero_desc": "Các gói ưu đãi được thiết kế riêng cho từng nhu cầu. Đặt sớm để nhận giá tốt nhất!",
    "offers.flash_title": "Ưu đãi có thời hạn",
    "offers.packages_title": "Gói nghỉ dưỡng trọn vẹn",
    "offers.book_now": "Đặt ngay",
    "admin.wrong_password": "Mật khẩu không đúng. Vui lòng thử lại.",
    "admin.enter_password": "Vui lòng nhập mật khẩu",
    "admin.area_title": "Khu vực Admin",
    "admin.enter_prompt": "Nhập mật khẩu quản trị để tiếp tục",
    "admin.password_label": "Mật khẩu Admin",
    "admin.password_placeholder": "Nhập mật khẩu...",
    "admin.authenticating": "Đang xác thực...",
    "admin.login_button": "Đăng nhập Admin",
    "admin.authorized_only": "Chỉ dành cho nhân viên được ủy quyền.",
    "admin.unauthorized_warning": "Truy cập trái phép sẽ bị ghi lại.",
    "admin.back_home": "Quay về trang chủ",
    "upsell.category_room_upgrade": "Nâng cấp phòng",
    "upsell.category_food": "Ăn uống",
    "upsell.category_spa": "Spa & Thư giãn",
    "upsell.category_transport": "Di chuyển",
    "upsell.category_activity": "Hoạt động",
    "upsell.category_amenity": "Tiện ích",
    "upsell.success_message": "dịch vụ vào booking của bạn. Chúng tôi sẽ chuẩn bị sẵn sàng khi bạn đến!",
    "upsell.greeting": "Chào {name}! Dựa trên booking của bạn, AI đề xuất những dịch vụ sau:",
    "upsell.wonderful": "Tuyệt vời!",
    "upsell.added_count": "Đã thêm {count}",
    "upsell.ai_special": "AI Gợi ý đặc biệt",
    "upsell.elevate_title": "Nâng tầm trải nghiệm của bạn",
    "upsell.add_to_booking": "Thêm vào booking",
    "upsell.skip": "Bỏ qua",
    "upsell.added_to_booking": "Đã thêm vào booking",
    "upsell.complete": "Hoàn tất",
    "upsell.services_selected": "dịch vụ đã chọn",
    "upsell.skip_continue": "Bỏ qua, tiếp tục",
    "upsell.add_later": "Bạn có thể thêm dịch vụ sau khi đến khách sạn",
    "upsell.no_suggestions": "Không có gợi ý nào lúc này",
    "hero.select_date": "Chọn ngày",
    "rooms.view_detail": "Xem chi tiết",
    "offers.note": "Giá đã bao gồm thuế VAT. Ưu đãi có thể thay đổi theo mùa và tình trạng phòng. Liên hệ lễ tân để được tư vấn gói phù hợp nhất.",
  },
  en: {
    // Nav
    "nav.home": "Home",
    "nav.rooms": "Rooms",
    "nav.amenities": "Amenities",
    "nav.offers": "Offers",
    "nav.explore": "Explore Hue",
    "nav.loyalty": "Loyalty",
    "nav.about": "About",
    "nav.contact": "Contact",
    "nav.book_now": "Book Now",
    "nav.points": "points",

    // Hero
    "hero.welcome": "WELCOME TO",
    "hero.tagline": "Your cozy retreat in the heart of Hue",
    "hero.badge1": "Comfortable Rooms",
    "hero.badge2": "Prime Location",
    "hero.badge3": "3-Star Comfort",
    "hero.chat_placeholder": "Hello! What kind of stay are you looking for?",
    "hero.checkin": "Check-in",
    "hero.checkout": "Check-out",
    "hero.guests": "Guests",
    "hero.search": "Search",
    "hero.guests_format": "{adults} guests, {rooms} room",

    // Features
    "features.title": "Special Experiences at The Imperial Hue",
    "features.subtitle": "The ideal retreat blending modern comfort with the culture of the ancient capital",
    "features.f1_title": "Central Location",
    "features.f1_desc": "Right in the heart of Hue, near the Imperial Citadel, Dong Ba Market and famous attractions",
    "features.f2_title": "Cozy Rooms",
    "features.f2_desc": "Modern design with the graceful charm of Hue",
    "features.f3_title": "Local Experiences",
    "features.f3_desc": "Curated itineraries, cuisine and culture unique to Hue",
    "features.f4_title": "Dedicated Service",
    "features.f4_desc": "Friendly team, always ready to accompany you",

    // Rooms section
    "rooms.title": "Our Rooms",
    "rooms.subtitle": "Choose the perfect space for your stay",
    "rooms.view_all": "View all rooms",
    "rooms.book": "Book Room",
    "rooms.from": "From",
    "rooms.guests": "guests",
    "rooms.sqm": "m²",
    "rooms.high_season": "Peak Season",
    "rooms.discount": "Special Price",
    "rooms.original_price": "Original Price",

    // Booking
    "booking.title": "Book a Room",
    "booking.room": "Room",
    "booking.checkin": "Check-in Date",
    "booking.checkout": "Check-out Date",
    "booking.guests": "Number of Guests",
    "booking.name": "Full Name",
    "booking.email": "Email",
    "booking.phone": "Phone Number",
    "booking.notes": "Notes",
    "booking.notes_placeholder": "Special requests, expected arrival time...",
    "booking.nights": "nights",
    "booking.total": "Total",
    "booking.submit": "Confirm Booking",
    "booking.success": "Booking Successful!",
    "booking.success_msg": "We will contact you to confirm within 24 hours.",
    "booking.login_required": "Please log in to book a room",
    "booking.login_btn": "Log in to Book",
    "booking.price_breakdown": "Price Breakdown",
    "booking.base_price": "Base Price",
    "booking.multiplier": "Price Multiplier",
    "booking.dynamic_price": "Applied Price",

    // Rooms page
    "rooms_page.title": "Rooms",
    "rooms_page.subtitle": "Discover refined accommodation at The Imperial Hue",
    "rooms_page.filter_all": "All",
    "rooms_page.sort_price_asc": "Price: Low to High",
    "rooms_page.sort_price_desc": "Price: High to Low",
    "rooms_page.sort_size": "Room Size",
    "rooms_page.no_rooms": "No rooms found",
    "rooms_page.available": "Available",
    "rooms_page.unavailable": "Unavailable",

    // Room detail
    "room_detail.back": "Go Back",
    "room_detail.book_now": "Book Now",
    "room_detail.amenities": "Room Amenities",
    "room_detail.description": "Description",
    "room_detail.capacity": "Capacity",
    "room_detail.size": "Room Size",
    "room_detail.bed": "Bed Type",

    // Loyalty
    "loyalty.title": "Loyalty Program",
    "loyalty.points": "Reward Points",
    "loyalty.history": "Points History",
    "loyalty.redeem": "Redeem Points",
    "loyalty.login_required": "Log in to view your reward points",

    // Common
    "common.loading": "Loading...",
    "common.error": "An error occurred",
    "common.back": "Back",
    "common.save": "Save",
    "common.cancel": "Cancel",
    "common.confirm": "Confirm",
    "common.close": "Close",
    "common.night": "night",
    "common.nights": "nights",
    "common.per_night": "/night",
    "common.vnd": "₫",
    "common.login": "Log In",
    "common.logout": "Log Out",
    "common.guest": "Guest",
    "common.guests": "guests",
    "common.room": "room",
    "common.rooms": "rooms",

    // Trust badges
    "trust.best_price": "Best Price Guarantee",
    "trust.best_price_desc": "Guaranteed best rates",
    "trust.free_cancel": "Free Cancellation",
    "trust.free_cancel_desc": "Cancel free up to 48h before",
    "trust.breakfast": "Free Breakfast",
    "trust.breakfast_desc": "Hue specialty buffet daily",
    "trust.wifi": "Free Wi-Fi",
    "trust.wifi_desc": "High-speed throughout the hotel",

    // Amenities page
    "amenities.title": "Amenities & Services",
    "amenities.subtitle": "Experience modern amenities blended with the graceful culture of Hue for a comfortable and memorable stay.",
    "amenities.standard": "3-Star Standard",
    "amenities.support": "Support",
    "amenities.rating": "Rating",
    "amenities.room_amenities": "In-Room Amenities",
    "amenities.hotel_facilities": "Hotel Facilities",
    "amenities.services": "Services & Utilities",
    "amenities.dining": "Dining",
    "amenities.wellness": "Sports & Wellness",
    "amenities.wifi": "High-Speed Wi-Fi",
    "amenities.wifi_desc": "Free throughout the hotel, 100Mbps speed",
    "amenities.ac": "Central Air Conditioning",
    "amenities.ac_desc": "Individual temperature control per room",
    "amenities.tv": "43-inch Smart TV",
    "amenities.tv_desc": "Netflix, YouTube and cable TV support",
    "amenities.safe": "In-Room Safe",
    "amenities.safe_desc": "Electronic safe in every room",
    "amenities.breakfast": "Free Breakfast",
    "amenities.breakfast_desc": "Hue specialty buffet every morning 6:30 \u2013 10:00",
    "amenities.restaurant": "The Garden Restaurant",
    "amenities.restaurant_desc": "Hue and international cuisine 11:00 \u2013 22:00",
    "amenities.cafe": "Caf\u00e9 & Bar Imperial",
    "amenities.cafe_desc": "Coffee, cocktails and beverages 7:00 \u2013 23:00",
    "amenities.room_service": "Room Service 24/7",
    "amenities.room_service_desc": "Order food and drinks to your room anytime",
    "amenities.pool": "Outdoor Swimming Pool",
    "amenities.pool_desc": "25m pool, open 6:00 \u2013 21:00",
    "amenities.gym": "Modern Fitness Center",
    "amenities.gym_desc": "Fully equipped, open 24/7",
    "amenities.spa": "Spa & Massage",
    "amenities.spa_desc": "Traditional Hue relaxation therapies",
    "amenities.sauna": "Sauna & Steam Room",
    "amenities.sauna_desc": "Dry and wet steam rooms",
    "amenities.airport": "Airport Transfer",
    "amenities.airport_desc": "Private car to/from Phu Bai Airport",
    "amenities.parking": "Free Parking",
    "amenities.parking_desc": "Covered parking for hotel guests",
    "amenities.tours": "Hue Sightseeing Tours",
    "amenities.tours_desc": "Book tours to the Imperial Citadel, royal tombs, Perfume River",
    "amenities.reception": "24/7 Front Desk",
    "amenities.reception_desc": "Check-in/check-out support and travel advice",
    "amenities.cta_title": "Ready to Experience?",
    "amenities.cta_desc": "Book today and enjoy all premium amenities at The Imperial Hue.",
    "amenities.cta_btn": "View Rooms & Book Now",
    // Offers pagee
    "offers.subtitle": "Discover attractive packages at The Imperial Hue",

    // Explore page
    "explore.title": "Explore Hue",
    "explore.subtitle": "Must-visit destinations in the ancient capital of Hue",

    // About page
    "about.title": "About Us",
    "about.subtitle": "The story of The Imperial Hue",

    // Contact page
    "contact.subtitle": "We are always ready to assist you",

    // Chat
    "chat.placeholder": "How can we help you?",
    "chat.error": "Sorry, I encountered an issue. Please try again!",
    "chat.q1": "Find Rooms",
    "chat.q1_sub": "Check availability",
    "chat.q1_msg": "I want to find available rooms",
    "chat.q2": "Special Offers",
    "chat.q2_sub": "Explore latest deals",
    "chat.q2_msg": "Are there any special offers?",
    "chat.q3": "Our Services",
    "chat.q3_sub": "Explore amenities & services",
    "chat.q3_msg": "What services does the hotel offer?",
    "chat.q4": "Get Support",
    "chat.q4_sub": "We are always ready!",
    "chat.q4_msg": "I need support",

    // Rooms page extra
    "rooms_page.search_placeholder": "Search room name...",
    "rooms_page.guests_label": "Guests",
    "rooms_page.sort_label": "Sort by",
    "rooms_page.price": "Price",
    "rooms_page.try_other": "Try changing filters or search terms",
    "rooms_page.rooms_found": "rooms found",
    "rooms_page.people_viewing": "people viewing",
    "rooms.view_details": "View Details",
    "rooms.tooltip": "This room is often fully booked on weekends. Would you like to check availability?",

    // Returning visitor
    "returning.best_price_kept": "We still have",
    "returning.room_viewed": "Room you viewed",
    "returning.view_rooms": "View Rooms",
    "chat.special_offer_for_you": "Special offer just for you!",
    "chat.view_offers": "View offers →",
    "chat.welcome_message": "Hello! 👋 I'm Imperial AI, your assistant at The Imperial Hue. I can help you find the perfect room or answer any questions about the hotel. How can I help?",
    "chat.error_message": "Sorry, an error occurred. Please try again.",
    "chat.input_placeholder": "Type your question...",
    "chat.mobile_placeholder": "Ask AI about rooms...",
    "chat.support_247": "24/7 Support",
    "exit.limited_offer": "Limited offer",
    "exit.wait_title": "Wait! We have a",
    "exit.special_offer": "special offer",
    "exit.for_you": "for you",
    "exit.room_viewing": "Room you're viewing",
    "exit.today_special": "Today's special offer",
    "exit.discount_all": "15% off all rooms",
    "exit.book_today": "Valid when booking today",
    "exit.expires_in": "Offer expires in:",
    "exit.claim_now": "Claim offer now →",
    "exit.no_thanks": "No, I don't need this offer",
    "returning.welcome": "Welcome back!",
    "returning.kept": "We still have the",
    "returning.best_price": "best prices",
    "returning.for_you": "for you.",
    "returning.new_offers": "New Offers",

    // Room detail extra
    "room_detail.people_viewing": "people viewing this room",
    "room_detail.price_per_night": "/night",
    "room_detail.select_dates": "Select dates to book",
    "room_detail.similar_rooms": "Similar Rooms",
    "room_detail.reviews": "Reviews",
    "room_detail.location": "Location",
    "room_detail.policies": "Policies",
    "room_detail.checkin_time": "Check-in: 2:00 PM",
    "room_detail.checkout_time": "Check-out: 12:00 PM",
    "room_detail.no_smoking": "No smoking",
    "room_detail.pets": "No pets allowed",

    // Booking extra
    "booking.special_requests": "Special Requests",
    "booking.payment_info": "Payment Information",
    "booking.pay_at_hotel": "Pay at hotel",
    "booking.booking_policy": "Booking Policy",
    "booking.free_cancel_48h": "Free cancellation up to 48 hours before",
    "booking.confirm_info": "Confirm Information",

    // About page extra
    "about.story": "Our Story",
    "about.story_desc": "The Imperial Hue was founded with a love for the ancient capital of Hue, aiming to provide warm and culturally rich accommodation experiences for travelers.",
    "about.mission": "Our Mission",
    "about.mission_desc": "Delivering comfortable stays that blend traditional Hue beauty with modern amenities.",
    "about.values": "Core Values",
    "about.value1": "Dedicated Service",
    "about.value2": "Cultural Preservation",
    "about.value3": "Sustainable Development",

    // Contact page extra
    "contact.address_value": "15 Ly Thuong Kiet, Hue City, Thua Thien Hue",
    "contact.phone": "Phone",
    "contact.email": "Email",
    "contact.send_message": "Send a Message",
    "contact.your_name": "Your Name",
    "contact.your_email": "Your Email",
    "contact.message": "Message",
    "contact.send": "Send",

    // Offers page extraa
    "offers.valid_until": "Valid until",
    "offers.terms": "Terms apply",

    // Explore page extra
    "explore.distance": "Distance",
    "explore.from_hotel": "from hotel",
    "explore.view_map": "View Map",
    "explore.must_visit": "Must Visit",
    "explore.ancient_capital": "Ancient Capital",
    "explore.hero_desc": "Discover amazing destinations, unique cuisine and cultural experiences in Hue",
    "explore.top_attractions": "Top Attractions",
    "explore.near_hotel": "Near our hotel",
    "explore.citadel": "Imperial Citadel of Hue",
    "explore.citadel_desc": "UNESCO World Heritage Site, the royal palace complex of the Nguyen Dynasty with unique architecture",
    "explore.perfume_river_bridge": "Perfume River & Truong Tien Bridge",
    "explore.perfume_river_desc": "Romantic symbol of Hue, most beautiful at sunset",
    "explore.tuduc": "Tu Duc Royal Tomb",
    "explore.tuduc_desc": "The most beautiful tomb in Hue with harmonious architecture between nature and art",
    "explore.thienmu": "Thien Mu Pagoda",
    "explore.thienmu_desc": "The oldest pagoda in Hue, a spiritual symbol on the banks of the Perfume River",
    "explore.cat_history": "History",
    "explore.cat_nature": "Nature",
    "explore.cat_spiritual": "Spiritual",
    "explore.hours_3_4": "3-4 hours",
    "explore.hours_2_3": "2-3 hours",
    "explore.hours_1_2": "1-2 hours",
    "explore.featured": "Featured",
    "explore.architecture": "Architecture",
    "explore.local_cuisine": "Hue Local Cuisine",
    "explore.bun_bo": "Bun Bo Hue",
    "explore.bun_bo_desc": "Hue's signature dish with rich broth, lemongrass and chili",
    "explore.bun_bo_where": "Ba Phuong, 323 Nguyen Sinh Cung",
    "explore.com_hen": "Com Hen",
    "explore.com_hen_desc": "Rice mixed with Perfume River clams, fresh herbs and spicy fish sauce",
    "explore.com_hen_where": "Dong Ba Market, Tran Hung Dao St.",
    "explore.banh_khoai": "Banh Khoai",
    "explore.banh_khoai_desc": "Crispy pancake with shrimp and pork, served with special dipping sauce",
    "explore.banh_khoai_where": "Hang Me, 11 Pho Duc Chinh",
    "explore.che_hue": "Che Hue",
    "explore.che_hue_desc": "Over 30 types of traditional sweet desserts, colorful and refreshing",
    "explore.che_hue_where": "Che Hem, 17 Hung Vuong",
    "explore.experiences": "Experiences in Hue",
    "explore.act_bike": "Cycling Adventure",
    "explore.act_bike_desc": "Rent a bike at the hotel and explore the old town and traditional craft villages",
    "explore.act_photo": "Ao Dai Photography",
    "explore.act_photo_desc": "Rent traditional Ao Dai and take photos at the Citadel, tombs and scenic spots",
    "explore.act_cooking": "Hue Cooking Class",
    "explore.act_cooking_desc": "Join a cooking class with local chefs, learn to make Banh Beo and Banh Nam",
    "explore.act_cruise": "Perfume River Cruise",
    "explore.act_cruise_desc": "Watch the sunset on the Perfume River while enjoying traditional Hue music on a boat",
    "explore.hotel_location": "Hotel Location",
    "explore.hotel_address": "123 Le Loi, Vinh Ninh, Hue City",
    "explore.hotel_nearby": "500m from Imperial Citadel • 300m from Perfume River",


    // About page
    "about.hero_title": "About\nThe Imperial Hue",
    "about.hero_desc": "Founded in 2015 with a love for the ancient capital, The Imperial Hue Boutique Hotel is where the timeless charm of Hue meets modern comfort.",
    "about.stat_years": "Years of Experience",
    "about.stat_rooms": "Rooms",
    "about.stat_guests": "Guests Served",
    "about.stat_rating": "Average Rating",
    "about.story_title": "Our Story",
    "about.story_p1": "The Imperial Hue was born from the dream of Hue natives who wanted to showcase their homeland\'s beauty to friends both domestic and international. Located right in the city center, just 500 meters from the Imperial Citadel.",
    "about.story_p2": "With 60 rooms equipped with modern amenities, a restaurant serving Hue royal cuisine, and a passionate team of staff, The Imperial Hue has become a favorite destination.",
    "about.story_p3": "In 2024, we pioneered the integration of AI Agent into hotel services \u2013 helping guests find rooms, book services, and explore Hue in a smarter way.",
    "about.value1_title": "Guest-Centric Care",
    "about.value1_desc": "Every guest is family. We listen and respond to the smallest needs.",
    "about.value2_title": "Consistent Quality",
    "about.value2_desc": "3-star standards maintained rigorously in every detail.",
    "about.value3_title": "Local Identity",
    "about.value3_desc": "We proudly bring Hue culture into every experience.",
    "about.value4_title": "Continuous Innovation",
    "about.value4_desc": "Applying AI technology to personalize experiences.",
    "about.timeline_title": "Our Journey",
    "about.milestone_2015": "Founded The Imperial Hue Boutique Hotel with 30 rooms",
    "about.milestone_2017": "Expanded to 60 rooms, achieved national 3-star certification",
    "about.milestone_2019": "Won \'Best Boutique Hotel in Central Vietnam\' award",
    "about.milestone_2022": "Launched The Garden restaurant, serving Hue royal cuisine",
    "about.milestone_2024": "Integrated AI Agent \u2013 the first smart travel assistant in Hue",
    "about.team_title": "Leadership Team",
    "about.team1_name": "Nguyen Minh Tuan",
    "about.team1_role": "General Director",
    "about.team1_desc": "15 years of experience in premium hospitality.",
    "about.team2_name": "Tran Thi Lan Anh",
    "about.team2_role": "Service Director",
    "about.team2_desc": "Customer experience specialist.",
    "about.team3_name": "Le Quang Huy",
    "about.team3_role": "Head Chef",
    "about.team3_desc": "Chef specializing in Hue royal cuisine.",
    "about.team4_name": "Pham Thi Thu Ha",
    "about.team4_role": "Marketing Manager",
    "about.team4_desc": "Digital marketing specialist.",

    // Contact page full
    "contact.support_247": "24/7 Support",
    "contact.reply_2h": "Reply within 2 hours",
    "contact.city_hue": "Hue City, Thua Thien Hue",
    "contact.hours": "Working Hours",
    "contact.reception_247": "Reception 24/7",
    "contact.checkin_checkout_time": "Check-in from 14:00 | Check-out 12:00",
    "contact.always_ready": "Always Ready to Help",
    "contact.title": "Contact Us",
    "contact.hero_desc": "The Imperial Hue team is always ready to assist you 24/7.",
    "contact.follow_us": "Follow Us",
    "contact.view_on_maps": "View on Google Maps \u2192",
    "contact.success_title": "Sent Successfully!",
    "contact.success_desc": "Thank you for contacting us. We will respond within 2 business hours.",
    "contact.send_another": "Send another message",
    "contact.form_desc": "Fill in the information below, we will get back to you as soon as possible.",
    "contact.fullname": "Full Name",
    "contact.fullname_placeholder": "John Doe",
    "contact.subject": "Subject",
    "contact.select_subject": "Select a subject...",
    "contact.subject_booking": "Booking & Pricing",
    "contact.subject_service": "Services & Amenities",
    "contact.subject_event": "Event Organization",
    "contact.subject_feedback": "Feedback & Suggestions",
    "contact.subject_other": "Other",
    "contact.message_placeholder": "Describe your request in detail...",
    "contact.address": "Address",

    // Booking page full
    "booking.invalid_room": "Invalid room",
    "booking.fill_all_fields": "Please fill in all required fields",
    "booking.success_message": "Booking successful! We will contact you soon.",
    "booking.error_message": "Booking error. Please try again.",
    "booking.room_not_found": "Room not found",
    "booking.guest_name": "Guest Name",
    "booking.guest_name_placeholder": "Enter your name",
    "booking.guest_unit": "guest(s)",
    "booking.ai_support_title": "\ud83d\udca1 Need help? We can assist you with your booking!",
    "booking.ai_support_desc": "Click the chat button in the bottom right corner to talk with our AI Assistant.",
    "booking.submitting": "Processing...",
    "booking.confirm_booking": "Confirm Booking",
    "booking.go_back": "Go Back",
    "booking.price_summary": "Price Summary",
    "booking.calculating_price": "Calculating dynamic price...",
    "booking.base_price_night": "Base price/night",
    "booking.night": "night",
    "booking.num_nights": "Number of nights",
    "booking.savings": "Savings",

    // Loyalty page full
    "loyalty.perk_earn_1x": "Earn 1x points",
    "loyalty.perk_earn_2x": "Earn 2x points",
    "loyalty.perk_birthday_10": "Birthday +10%",
    "loyalty.perk_birthday_15": "Birthday +15%",
    "loyalty.perk_birthday_20": "Birthday +20%",
    "loyalty.perk_birthday_30": "Birthday +30%",
    "loyalty.perk_early_checkin": "Early check-in",
    "loyalty.perk_early_checkin_priority": "Priority early check-in",
    "loyalty.perk_late_checkout_14": "Late checkout 14:00",
    "loyalty.perk_late_checkout_16": "Late checkout 16:00",
    "loyalty.perk_room_upgrade": "Room upgrade",
    "loyalty.perk_suite_upgrade": "Suite upgrade",
    "loyalty.perk_free_minibar": "Free minibar",
    "loyalty.perk_flexible_checkin": "Flexible check-in",
    "loyalty.perk_concierge": "Personal concierge",
    "loyalty.perk_free_spa": "Free spa",
    "loyalty.reward_discount_100k": "100,000 VND discount",
    "loyalty.reward_breakfast": "Free breakfast",
    "loyalty.reward_room_upgrade": "Room upgrade",
    "loyalty.reward_airport_transfer": "Airport transfer",
    "loyalty.reward_spa_60": "60-min spa session",
    "loyalty.reward_free_night": "1 free night",
    "loyalty.login_desc": "Log in to view your reward points and redeem gifts.",
    "loyalty.login_now": "Log In Now",
    "loyalty.subtitle": "Earn points, redeem rewards, enjoy exclusive benefits",
    "loyalty.tier": "Membership Tier",
    "loyalty.current_points": "Current Points",
    "loyalty.total_earned": "Total Earned",
    "loyalty.points_unit": "points",
    "loyalty.points_more": "more points",
    "loyalty.redeem_rewards": "Redeem Rewards",
    "loyalty.confirm_redeem": "Confirm redeem",
    "loyalty.processing": "Processing...",
    "loyalty.confirm": "Confirm",
    "loyalty.cancel": "Cancel",
    "loyalty.redeem_now": "Redeem Now",
    "loyalty.need_more": "Need more",
    "loyalty.no_transactions": "No transactions yet",
    "loyalty.no_account": "No Loyalty Account",
    "loyalty.no_account_desc": "Make your first booking to start earning points.",

    // Rooms page
    "rooms.filter_all": "All",
    "rooms.sort_price_asc": "Price: Low to High",
    "rooms.sort_price_desc": "Price: High to Low",
    "rooms.sort_capacity": "Capacity",
    "rooms.per_night": "/night",
    "rooms.no_rooms": "No rooms found",
    "rooms_page.ai_tooltip": "This room is often fully booked on weekends. Would you like to check availability?",
    "rooms_page.clear_filter": "Clear filters",
    "offers.badge_popular": "Most Popular",
    "offers.badge_family": "Family",
    "offers.badge_savings": "Savings",
    "offers.badge_longstay": "Long Stay",
    "offers.honeymoon_title": "Honeymoon Package",
    "offers.honeymoon_desc": "A complete romantic getaway in Hue with your loved one. Includes Deluxe Balcony room, private dinner by the Perfume River, fresh flowers and welcome wine.",
    "offers.family_title": "Family Fun Package",
    "offers.family_desc": "A perfect family vacation with spacious rooms, buffet breakfast and exciting Hue exploration activities for children.",
    "offers.weekend_title": "Weekend Getaway Package",
    "offers.weekend_desc": "Escape the busy life and enjoy a relaxing weekend at The Imperial Hue with full amenities and care services.",
    "offers.business_title": "Extended Business Stay",
    "offers.business_desc": "Ideal for business travelers or long-stay guests. Enjoy special rates when staying 5 nights or more.",
    "offers.flash_friday": "Friday Flash Sale",
    "offers.flash_friday_desc": "30% off all rooms booked on Fridays",
    "offers.flash_friday_expires": "2 days left",
    "offers.early_bird_desc": "Book 30 days ahead, save 25%",
    "offers.early_bird_expires": "Always available",
    "offers.last_minute_desc": "Rooms available today, 15% off if booked before 18:00",
    "offers.last_minute_expires": "Today",
    "offers.special_tag": "Special Offers",
    "offers.title": "Offers & Promotions",
    "offers.hero_desc": "Packages designed for every need. Book early for the best rates!",
    "offers.flash_title": "Limited-Time Offers",
    "offers.packages_title": "Complete Stay Packages",
    "offers.book_now": "Book Now",
    "admin.wrong_password": "Incorrect password. Please try again.",
    "admin.enter_password": "Please enter password",
    "admin.area_title": "Admin Area",
    "admin.enter_prompt": "Enter admin password to continue",
    "admin.password_label": "Admin Password",
    "admin.password_placeholder": "Enter password...",
    "admin.authenticating": "Authenticating...",
    "admin.login_button": "Login Admin",
    "admin.authorized_only": "Authorized personnel only.",
    "admin.unauthorized_warning": "Unauthorized access will be logged.",
    "admin.back_home": "Back to homepage",
    "upsell.category_room_upgrade": "Room Upgrade",
    "upsell.category_food": "Food & Beverage",
    "upsell.category_spa": "Spa & Wellness",
    "upsell.category_transport": "Transportation",
    "upsell.category_activity": "Activities",
    "upsell.category_amenity": "Amenities",
    "upsell.success_message": "services added to your booking. We will have everything ready for your arrival!",
    "upsell.greeting": "Hello {name}! Based on your booking, AI recommends the following services:",
    "upsell.wonderful": "Wonderful!",
    "upsell.added_count": "Added {count}",
    "upsell.ai_special": "AI Special Recommendations",
    "upsell.elevate_title": "Elevate your experience",
    "upsell.add_to_booking": "Add to booking",
    "upsell.skip": "Skip",
    "upsell.added_to_booking": "Added to booking",
    "upsell.complete": "Complete",
    "upsell.services_selected": "services selected",
    "upsell.skip_continue": "Skip, continue",
    "upsell.add_later": "You can add services after arriving at the hotel",
    "upsell.no_suggestions": "No suggestions available at this time",
    "hero.select_date": "Select date",
    "rooms.view_detail": "View details",
    "offers.note": "Prices include VAT. Offers may change based on season and room availability. Contact reception for the best package recommendation.",
  },
};

// ─── Provider ─────────────────────────────────────────────────────────────────
export function LanguageProvider({ children }: { children: ReactNode }) {
  const [lang, setLangState] = useState<Language>(() => {
    const saved = localStorage.getItem("imperial_lang");
    return (saved === "en" || saved === "vi") ? saved : "vi";
  });

  const setLang = (newLang: Language) => {
    setLangState(newLang);
    localStorage.setItem("imperial_lang", newLang);
  };

  const t = (key: string): string => {
    return translations[lang][key] ?? translations["vi"][key] ?? key;
  };

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

// ─── Hook ─────────────────────────────────────────────────────────────────────
export function useLanguage() {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error("useLanguage must be used within LanguageProvider");
  return ctx;
}
